### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [Broadroad/storageserver#1]
Hi @Broadroad . I'm a graphic designer. I wanted to contribute to your awesome project and I've designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr. If you need anything change please let me know, i'll fix it and make it better. If you have an idea please share with me, it would be better for me. Thank you
Best regard.
[Mirza Zulfan](https://github.com/mirzazulfan/Portfolio)
![ss](https://user-images.githubusercontent.com/36124339/42614462-3c48ad4c-85d0-11e8-8063-a6135014ecb1.png)

**Comment by Broadroad** [comment]
hi @mirzazulfan . Cool, you can create a PR. I think Blue is better for this project. Thank you very much

**Comment by mirzazulfan** [comment]
I'm glad you liked it. I'll create a pull request and upload the files.

**Comment by mirzazulfan** [comment]
Hi @Broadroad . You can download all files [Here](https://drive.google.com/drive/folders/1x7c16sQ8hhWWHVWJ5rO_EGdWJDcj42oj?ogsrc=32) . Here's the pr #2 .
Thank you. Best Regard.

**Comment by mirzazulfan** [comment]
Hi @Broadroad . If you need anything changes in the future, dont hesitate to contact me, 
Email : mirzazulfan@gmail.com
Have a nice day.
